### ISSUE TITLE
RangeError on discover - Trying to access beyond buffer length

### ISSUE THREAD

**Issue by holmesal** [noble/noble#25]
This error seems to be thrown when this Flex is discovered:

```
buffer.js:579
    throw new RangeError('Trying to access beyond buffer length');
          ^
RangeError: Trying to access beyond buffer length
    at checkOffset (buffer.js:579:11)
    at Buffer.readUInt8 (buffer.js:585:5)
    at HciBle.onStdoutData (/home/pi/robin-pi/node_modules/noble/lib/linux/hci-ble.js:84:24)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:720:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:392:10)
    at emitReadable (_stream_readable.js:388:5)
    at readableAddChunk (_stream_readable.js:150:9)
    at Socket.Readable.push (_stream_readable.js:113:10)
```

Here's the hci-ble debug logs for that device, immediately before the error is thrown:

```
  hci-ble buffer = "event F8:84:8D:C6:86:4A,random,0201061106ba5689a6fabfa2bd01467d6e00fb3e15020104014a86,-58\n" +11ms
  hci-ble line = event F8:84:8D:C6:86:4A,random,0201061106ba5689a6fabfa2bd01467d6e00fb3e15020104014a86,-58 +3ms
  hci-ble address = F8:84:8D:C6:86:4A +3ms
  hci-ble addressType = random +3ms
  hci-ble eir = 0201061106ba5689a6fabfa2bd01467d6e00fb3e15020104014a86 +2ms
  hci-ble rssi = -58 +3ms
```

Strangely, this Flex seems to have been discovered without error in an earlier scan:

```
  hci-ble buffer = "event F8:84:8D:C6:86:4A,random,0201061106ba5689a6fabfa2bd01467d6e00fbabad05160a180706,-81\nevent F8:84:8D:C6:86:4A,random,0509466c6578020afa,-81\n" +461ms
  hci-ble line = event F8:84:8D:C6:86:4A,random,0201061106ba5689a6fabfa2bd01467d6e00fbabad05160a180706,-81 +4ms
  hci-ble address = F8:84:8D:C6:86:4A +7ms
  hci-ble addressType = random +4ms
  hci-ble eir = 0201061106ba5689a6fabfa2bd01467d6e00fbabad05160a180706 +5ms
  hci-ble rssi = -81 +5ms
  hci-ble advertisement = {"localName":"Flex","serviceData":[10,24,7,6],"txPowerLevel":-6,"serviceUuids":["adab08f36e7d4601bda2bffaa68956ba","adabfb006e7d4601bda2bffaa68956ba"]} +4ms
  hci-ble line = event F8:84:8D:C6:86:4A,random,0509466c6578020afa,-81 +6ms
  hci-ble address = F8:84:8D:C6:86:4A +7ms
  hci-ble addressType = random +2ms
  hci-ble eir = 0509466c6578020afa +3ms
  hci-ble rssi = -81 +2ms
  hci-ble advertisement = {"localName":"Flex","serviceData":[10,24,7,6],"txPowerLevel":-6,"serviceUuids":["adab08f36e7d4601bda2bffaa68956ba","adabfb006e7d4601bda2bffaa68956ba"]} +4ms
```

Any idea what's going on here?

**Comment by PimButton** [comment]
I'm getting the RangeError when running the peripheral-explorer example. I'm on windows, using a fresh install of both Noble and Async. 
```
Your environment has been set up for using Node.js 0.12.7 (ia32) and npm.

C:\Users\Kokkerelletje\Documents\VanErum\PC Applicatie\testNoble>node test.js
buffer.js:506
    throw new RangeError('index out of range');
          ^
RangeError: index out of range
    at checkOffset (buffer.js:506:11)
    at Buffer.readUInt8 (buffer.js:544:5)
    at BluetoothHciSocket.onHciEventEndpointData (C:\Users\Kokkerelletje\Documents\VanErum\PC Applicatie\testNoble\node_modules\noble\node_modules\bluetooth-hci
-socket\lib\usb.js:115:36)
    at InEndpoint.emit (events.js:107:17)
    at Transfer.transferDone (C:\Users\Kokkerelletje\Documents\VanErum\PC Applicatie\testNoble\node_modules\noble\node_modules\bluetooth-hci-socket\node_modules
\usb\usb.js:295:9)
```

Any ideas? Would like to provide more debug data, how do I enable this?
