### ISSUE TITLE
peripheral-explorer example fails with newer async

### ISSUE THREAD

**Issue by don** [noble/noble#757]
The peripheral-explorer.js example breaks with async 2.6.0

    $ node peripheral-explorer.js 1bf3c5b55707492b890d31373aaf5cd8
    peripheral with ID 1bf3c5b55707492b890d31373aaf5cd8 found
      Local Name        = Demo
      Service Data      = []
      Service UUIDs     = abc0

    services and characteristics:
    abc0
    /Users/don/noble/examples/peripheral-explorer.js:102
                                userDescriptionDescriptor.readValue(function(error, data) {
                                                          ^

    TypeError: userDescriptionDescriptor.readValue is not a function
        at /Users/don/noble/examples/peripheral-explorer.js:102:55
        at /Users/don/noble/node_modules/async/dist/async.js:2790:17
        at /Users/don/noble/node_modules/async/dist/async.js:473:16
        at iteratorCallback (/Users/don/noble/node_modules/async/dist/async.js:1048:13)
        at /Users/don/noble/node_modules/async/dist/async.js:958:16
        at /Users/don/noble/node_modules/async/dist/async.js:2779:21
        at /Users/don/noble/examples/peripheral-explorer.js:98:34
        at /Users/don/noble/node_modules/async/dist/async.js:2777:13
        at eachOfArrayLike (/Users/don/noble/node_modules/async/dist/async.js:1055:9)
        at eachOf (/Users/don/noble/node_modules/async/dist/async.js:1103:5)

Sample peripheral for Arduino 101

    #include <CurieBLE.h>

    BLEPeripheral blePeripheral;
    BLEService service = BLEService("ABC0");
    BLECharCharacteristic characteristic = BLECharCharacteristic("ACB1", BLERead | BLEWrite | BLENotify);
    BLEDescriptor descriptor = BLEDescriptor("2901", "User Description");

    void setup() {
      blePeripheral.setLocalName("Demo");
      blePeripheral.setAdvertisedServiceUuid(service.uuid());  
      blePeripheral.addAttribute(service);
      blePeripheral.addAttribute(characteristic);
      blePeripheral.addAttribute(descriptor);
      blePeripheral.begin();
      characteristic.setValue(0x11);
    }

    void loop() {
      blePeripheral.poll();
    }

    cd /tmp
    git clone https://github.com/sandeepmistry/noble.git
    cd noble
    npm install
    npm install async@latest
    cd examples
    node advertisement-discovery.js

Look for Demo in the output. Copy the UUID. Run peripheral-explorer.js 

    node peripheral-explorer.js 1bf3c5b55707492b890d31373aaf5cd8

This works with async@0.2.10 but fails with async@2.6.0

**Comment by don** [comment]
See pull request https://github.com/sandeepmistry/noble/pull/758. Fix works with async@0.2.10 and async@2.6.0.

    $ node peripheral-explorer.js 1bf3c5b55707492b890d31373aaf5cd8
    peripheral with ID 1bf3c5b55707492b890d31373aaf5cd8 found
      Local Name        = Demo
      Service Data      = []
      Service UUIDs     = abc0

    services and characteristics:
    abc0
      acb1 (User Description)
        properties  read, write, notify
        value       11 | ''
