### ISSUE TITLE
Issue running StateChange in NW.js

### ISSUE THREAD

**Issue by fredbonkers** [noble/noble#775]
Trying to run this code in an HTML file in Node Webkit: 
`
        var noble = require('./index.js');

	noble.on('stateChange', function(state) {

	  if (state === 'poweredOn') {

		noble.startScanning();

		console.log("Scanning...");

	  } 

	  else {

		noble.stopScanning();

		console.log("Scanning stopped");

	  }

	});
`

...produces an error:
`
Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\F:\My_Code\Noble_test\node_modules\usb\src\binding\usb_bindings.node

    at Object.Module._extensions..node (module.js:721:18)
    at Module.load (module.js:586:32)
    at tryModuleLoad (module.js:526:12)
    at Function.Module._load (module.js:518:3)
    at Module.require (module.js:618:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\My_Code\NW.js\noble-master\simActiv\Noble_test\node_modules\usb\usb.js:5:38)
    at Module._compile (module.js:674:30)
    at Object.Module._extensions..js (module.js:691:10)
    at Module.load (module.js:586:32)
`

However, running it with node in a js file works fine. Am I doing something wrong, or is this a known problem?

**Comment by LorenzGardner** [comment]
nw.js has a different application interface than node, you have to recompile packages written in c++ nw-gyp.
