### ISSUE TITLE
Cannot find module '../build/Release/binding.node'

### ISSUE THREAD

**Issue by Lvf974** [noble/noble#799]
Hi, I tried to make this command to track communications of a connected object. And I have this mistake that I can't solve.

sudo node advertise.js -a devices/b4994c5f9e2d_AL-Bc7.adv.json -s devices/b4994c5f9e2d.srv.json 
module.js:549
    throw err;
    ^

Error: Cannot find module '../build/Release/binding.node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ludovic/node_modules/gattacker/node_modules/bluetooth-hci-socket/lib/native.js:3:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by don** [comment]
It sounds like something isn't built correctly. I'd remove `node_modules` in your project and run `npm install` again. If you still get error, please provide more info about the node version, os, architecture etc.

**Comment by ujj-u** [comment]
I am also facing the same issue. Tried reinstalling everything.

I am on arch I installed every bluez package. Arch is absent from nobel's readme file. Adding dependencies for Arch would be helpful.

**Comment by don** [comment]
@ujj-u we need more details. My guess is [bluetooth-hci-socket](https://github.com/noble/node-bluetooth-hci-socket) failed to compile. Make sure your system has all the dependencies. In addition to bluez you usually need libudev-dev, python2.7, make, gcc. I don't know anything about Arch but if you make suggestions, we can get the docs updated.

See if you can build bluetooth-hci-socket. I recommend using Node 8.x.

    cd ~
    git clone https://github.com/noble/node-bluetooth-hci-socket
    cd node-bluetooth-hci-socket
    npm install

If that works, try and build noble

    cd ~
    git clone https://github.com/noble/noble
    cd noble
    npm install
    cd examples/
    sudo node advertisement-discovery.js

**Comment by Lvf974** [comment]
I managed to install, my node version was not the same as the nodejs version

**Comment by yesimxev** [comment]
The above methods did not work for me. For anyone who needs another solution. Looks like the bindings.node can be just simply pasted where the program looks for it. Eg. use `strace YOUR_COMMAND` and check which folder is it being searching in.
Then 
```
git clone https://github.com/noble/node-bluetooth-hci-socket.git
mkdir -p /root/YOUR_PROGRAM/node_modules/noble/node_modules/bluetooth-hci-socket/build/Release
cp /root/node-bluetooth-hci-socket/build/Release/binding.node /root/YOUR_PROGRAM/node_modules/noble/node_modules/bluetooth-hci-socket/build/Release/
```

**Comment by sumitjaju** [comment]
> @ujj-u we need more details. My guess is [bluetooth-hci-socket](https://github.com/noble/node-bluetooth-hci-socket) failed to compile. Make sure your system has all the dependencies. In addition to bluez you usually need libudev-dev, python2.7, make, gcc. I don't know anything about Arch but if you make suggestions, we can get the docs updated.
> 
> See if you can build bluetooth-hci-socket. I recommend using Node 8.x.
> 
> ```
> cd ~
> git clone https://github.com/noble/node-bluetooth-hci-socket
> cd node-bluetooth-hci-socket
> npm install
> ```
> 
> If that works, try and build noble
> 
> ```
> cd ~
> git clone https://github.com/noble/noble
> cd noble
> npm install
> cd examples/
> sudo node advertisement-discovery.js
> ```

Don, when I issued npm install for node-bluetooth-hci-socket project it gives error of 'platform unsupported'. Is macos not supported. 

`npm ERR! notsup Unsupported platform for bluetooth-hci-socket@0.5.2: wanted {"os":"linux,android,freebsd,win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})`

Between I am trying to setup noble but gives me below error while I initialize node js program. Please advise. 

My machine spec: 
node 8.x
macosX Mojave


```
module.js:549
    throw err;
    ^

Error: Cannot find module './build/Release/binding.node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Meet/Front-workspace/startupnode/node_modules/xpc-connection/index.js:3:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by bugs181** [comment]
Having the same issue (with almost the same specs) as @sumitjaju 

`node -v`: `v12.12.0`
`npm -v`: `6.11.3`
`OS`: `OS X Mojave 10.14`

**Comment by yesimxev** [comment]
Replacing the line in the .cpp worked for me, or you can replace the whole folder
https://github.com/abandonware/node-bluetooth-hci-socket/commit/9b9e9753a6e676754a851369f723c1bbcf7783c6

**Comment by pvonmoradi** [comment]
Same issue for `v12.20.0` trying to get https://github.com/tralamazza/nus_console running.
```
node index.js 
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'noble'
Require stack:
- /home/some_dir/bluetooth/nus_console/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/some_dir/bluetooth/nus_console/index.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/some_dir/bluetooth/nus_console/index.js' ]
}
```

**Comment by solarkraft** [comment]
I have a similar looking error on an M1 Mac with node 16.15.0. 

Installing fails with: 

```
paul@KekBook noble-messing % yarn add noble
yarn add v1.22.18
warning package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
warning Error running install script for optional dependency: "/Users/paul/Documents/JawboneHacking/noble-messing/node_modules/xpc-connection: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/paul/Documents/JawboneHacking/noble-messing/node_modules/xpc-connection
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.0.0
gyp info using node@16.15.0 | darwin | arm64
gyp info find Python using Python version 3.8.9 found at \"/Library/Developer/CommandLineTools/usr/bin/python3\"
gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/paul/Documents/JawboneHacking/noble-messing/node_modules/xpc-connection/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/paul/Library/Caches/node-gyp/16.15.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/paul/Library/Caches/node-gyp/16.15.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/paul/Documents/JawboneHacking/noble-messing/node_modules/xpc-connection',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/binding/src/XpcConnection.o
../src/XpcConnection.cpp:26:77: error: too few arguments to function call, single argument 'context' was not specified
  target->Set(Nan::New(\"XpcConnection\").ToLocalChecked(), tmpl->GetFunction());
                                                          ~~~~~~~~~~~~~~~~~ ^
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:6802:46: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                             ^
../src/XpcConnection.cpp:26:11: error: no matching member function for call to 'Set'
  target->Set(Nan::New(\"XpcConnection\").ToLocalChecked(), tmpl->GetFunction());
  ~~~~~~~~^~~
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:3961:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:3964:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/XpcConnection.cpp:103:54: error: too few arguments to function call, single argument 'context' was not specified
    xpcObject = xpc_int64_create(value->IntegerValue());
                                 ~~~~~~~~~~~~~~~~~~~ ^
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:3101:40: note: 'IntegerValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
                                       ^
../src/XpcConnection.cpp:103:17: error: no matching function for call to 'xpc_int64_create'
    xpcObject = xpc_int64_create(value->IntegerValue());
                ^~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/xpc/xpc.h:591:1: note: candidate function not viable: no known conversion from 'Maybe<int64_t>' (aka 'Maybe<long long>') to 'int64_t' (aka 'long long') for 1st argument
xpc_int64_create(int64_t value);
^
../src/XpcConnection.cpp:113:49: error: too few arguments to function call, single argument 'context' was not specified
    Local<Object> valueObject = value->ToObject();
                                ~~~~~~~~~~~~~~~ ^
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:3060:44: note: 'ToObject' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
../src/XpcConnection.cpp:113:19: error: no viable conversion from 'MaybeLocal<v8::Object>' to 'Local<v8::Object>'
    Local<Object> valueObject = value->ToObject();
                  ^             ~~~~~~~~~~~~~~~~~
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:200:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:200:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:204:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:348:22: note: explicit constructor is not a candidate
  explicit V8_INLINE Local(T* that) : val_(that) {}
                     ^
../src/XpcConnection.cpp:115:78: error: too few arguments to function call, expected 2, have 1
    if (valueObject->HasRealNamedProperty(Nan::New(\"isUuid\").ToLocalChecked())) {
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                    ^
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:4250:37: note: 'HasRealNamedProperty' declared here
  V8_WARN_UNUSED_RESULT Maybe<bool> HasRealNamedProperty(Local<Context> context,
                                    ^
../src/XpcConnection.cpp:115:9: error: value of type 'Maybe<bool>' is not contextually convertible to 'bool'
    if (valueObject->HasRealNamedProperty(Nan::New(\"isUuid\").ToLocalChecked())) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/XpcConnection.cpp:123:49: error: too few arguments to function call, single argument 'context' was not specified
    Local<Object> valueObject = value->ToObject();
                                ~~~~~~~~~~~~~~~ ^
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:3060:44: note: 'ToObject' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
../src/XpcConnection.cpp:123:19: error: no viable conversion from 'MaybeLocal<v8::Object>' to 'Local<v8::Object>'
    Local<Object> valueObject = value->ToObject();
                  ^             ~~~~~~~~~~~~~~~~~
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:200:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:200:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:204:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:348:22: note: explicit constructor is not a candidate
  explicit V8_INLINE Local(T* that) : val_(that) {}
                     ^
../src/XpcConnection.cpp:135:40: error: no matching member function for call to 'GetPropertyNames'
  Local<Array> propertyNames = object->GetPropertyNames();
                               ~~~~~~~~^~~~~~~~~~~~~~~~
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:4115:43: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Array> GetPropertyNames(
                                          ^
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:4117:43: note: candidate function not viable: requires at least 4 arguments, but 0 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Array> GetPropertyNames(
                                          ^
../src/XpcConnection.cpp:138:48: error: no matching member function for call to 'Get'
    Local<Value> propertyName = propertyNames->Get(i);
                                ~~~~~~~~~~~~~~~^~~
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:4007:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:4010:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
../src/XpcConnection.cpp:143:88: error: too few arguments to function call, single argument 'context' was not specified
      Local<Value> propertyValue = object->GetRealNamedProperty(propertyName->ToString());
                                                                ~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:3048:44: note: 'ToString' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                           ^
../src/XpcConnection.cpp:143:89: error: too few arguments to function call, expected 2, have 1
      Local<Value> propertyValue = object->GetRealNamedProperty(propertyName->ToString());
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~                         ^
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:4278:43: note: 'GetRealNamedProperty' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> GetRealNamedProperty(
                                          ^
../src/XpcConnection.cpp:143:20: error: no viable conversion from 'MaybeLocal<v8::Value>' to 'Local<v8::Value>'
      Local<Value> propertyValue = object->GetRealNamedProperty(propertyName->ToString());
                   ^               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:200:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'MaybeLocal<v8::Value>' to 'const v8::Local<v8::Value> &' for 1st argument
class Local {
      ^
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:200:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'MaybeLocal<v8::Value>' to 'v8::Local<v8::Value> &&' for 1st argument
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:204:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:348:22: note: explicit constructor is not a candidate
  explicit V8_INLINE Local(T* that) : val_(that) {}
                     ^
../src/XpcConnection.cpp:160:33: error: no matching member function for call to 'Get'
    Local<Value> value = array->Get(i);
                         ~~~~~~~^~~
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:4007:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:4010:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
../src/XpcConnection.cpp:200:13: error: no matching member function for call to 'Set'
    object->Set(Nan::New<String>(key).ToLocalChecked(), XpcConnection::XpcObjectToValue(value));
    ~~~~~~~~^~~
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:3961:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:3964:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/XpcConnection.cpp:212:12: error: no matching member function for call to 'Set'
    array->Set(Nan::New<Number>(index), XpcConnection::XpcObjectToValue(value));
    ~~~~~~~^~~
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:3961:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/paul/Library/Caches/node-gyp/16.15.0/include/node/v8.h:3964:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/XpcConnection.cpp:254:12: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
      Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New(\"emit\").ToLocalChecked(), 2, argv);
           ^
../../nan/nan.h:1049:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:108:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/XpcConnection.cpp:263:12: warning: 'MakeCallback' is deprecated [-Wdeprecated-declarations]
      Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New(\"emit\").ToLocalChecked(), 2, argv);
           ^
../../nan/nan.h:1049:3: note: 'MakeCallback' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
  ^
../../nan/nan.h:108:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
2 warnings and 18 errors generated.
make: *** [Release/obj.target/binding/src/XpcConnection.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.4.0
gyp ERR! command \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/paul/Documents/JawboneHacking/noble-messing/node_modules/xpc-connection
gyp ERR! node -v v16.15.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
warning No license field
success Saved 1 new dependency.
info Direct dependencies
└─ noble@1.9.1
info All dependencies
└─ noble@1.9.1
✨  Done in 2.04s.
```

... then, when running, it fails with:

```
paul@KekBook noble-messing % node main.ts
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'xpc-connection'
Require stack:
- /Users/paul/Documents/JawboneHacking/noble-messing/node_modules/noble/lib/mac/highsierra.js
- /Users/paul/Documents/JawboneHacking/noble-messing/node_modules/noble/lib/mac/bindings.js
- /Users/paul/Documents/JawboneHacking/noble-messing/node_modules/noble/lib/resolve-bindings.js
- /Users/paul/Documents/JawboneHacking/noble-messing/node_modules/noble/index.js
- /Users/paul/Documents/JawboneHacking/noble-messing/main.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/paul/Documents/JawboneHacking/noble-messing/node_modules/noble/lib/mac/highsierra.js:7:21)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/paul/Documents/JawboneHacking/noble-messing/node_modules/noble/lib/mac/highsierra.js',
    '/Users/paul/Documents/JawboneHacking/noble-messing/node_modules/noble/lib/mac/bindings.js',
    '/Users/paul/Documents/JawboneHacking/noble-messing/node_modules/noble/lib/resolve-bindings.js',
    '/Users/paul/Documents/JawboneHacking/noble-messing/node_modules/noble/index.js',
    '/Users/paul/Documents/JawboneHacking/noble-messing/main.ts'
  ]
}
```

Interestingly installation using npm only shows the node-gyp error when installing xpc-connection explicitly. The runtime error is the same.

**Comment by maelp** [comment]
I still have this, on osX (the above module doesn't work for osX)
