### ISSUE TITLE
TypeError: uuids.indexOf is not a function

### ISSUE THREAD

**Issue by lastmjs** [noble/noble#806]
I'm trying to connect to a peripheral and discover its services, but I run into the following error. This is happening to me on multiple peripherals, I've printed one of them to the console, followed by the error that I receive:

```
Peripheral {
  _noble: 
   Noble {
     initialized: true,
     address: 'a0:88:69:6d:60:1d',
     _state: 'poweredOn',
     _bindings: 
      NobleBindings {
        _state: 'poweredOn',
        _addresses: [Object],
        _addresseTypes: [Object],
        _connectable: [Object],
        _pendingConnectionUuid: 'b827ebe7b33e',
        _connectionQueue: [],
        _handles: [Object],
        _gatts: [Object],
        _aclStreams: [Object],
        _signalings: [Object],
        _hci: [Object],
        _gap: [Object],
        _events: [Object],
        _eventsCount: 21,
        onSigIntBinded: [Function: bound ],
        _scanServiceUuids: [] },
     _peripherals: 
      { '5d59e26cf4e1': [Object],
        '17ac410e48fe': [Object],
        b827ebe7b33e: [Circular],
        d62b4cc60ac0: [Object] },
     _services: 
      { '5d59e26cf4e1': {},
        '17ac410e48fe': {},
        b827ebe7b33e: {},
        d62b4cc60ac0: {} },
     _characteristics: 
      { '5d59e26cf4e1': {},
        '17ac410e48fe': {},
        b827ebe7b33e: {},
        d62b4cc60ac0: {} },
     _descriptors: 
      { '5d59e26cf4e1': {},
        '17ac410e48fe': {},
        b827ebe7b33e: {},
        d62b4cc60ac0: {} },
     _discoveredPeripheralUUids: [ '5d59e26cf4e1', '17ac410e48fe', 'b827ebe7b33e', 'd62b4cc60ac0' ],
     _events: 
      { warning: [Function: bound ],
        newListener: [Function: bound ],
        stateChange: [Function],
        discover: [Function] },
     _eventsCount: 4,
     _allowDuplicates: true },
  id: 'b827ebe7b33e',
  uuid: 'b827ebe7b33e',
  address: 'b8:27:eb:e7:b3:3e',
  addressType: 'public',
  connectable: true,
  advertisement: 
   { localName: 'PORTAL',
     txPowerLevel: undefined,
     manufacturerData: undefined,
     serviceData: [],
     serviceUuids: [ 'd304dbd96fdc4bf3a617e015edd87ed5' ],
     solicitationServiceUuids: [],
     serviceSolicitationUuids: [] },
  rssi: -35,
  services: null,
  state: 'connected',
  _events: {},
  _eventsCount: 0 }
/home/lastmjs/development/portal-blue/door-device/node_modules/noble/lib/hci-socket/gatt.js:355
        if (uuids.length === 0 || uuids.indexOf(services[i].uuid) !== -1) {
                                        ^

TypeError: uuids.indexOf is not a function
    at Gatt.<anonymous> (/home/lastmjs/development/portal-blue/door-device/node_modules/noble/lib/hci-socket/gatt.js:355:41)
    at Gatt.onAclStreamData (/home/lastmjs/development/portal-blue/door-device/node_modules/noble/lib/hci-socket/gatt.js:132:26)
    at emitTwo (events.js:131:20)
    at AclStream.emit (events.js:214:7)
    at AclStream.push (/home/lastmjs/development/portal-blue/door-device/node_modules/noble/lib/hci-socket/acl-stream.js:35:10)
    at NobleBindings.onAclDataPkt (/home/lastmjs/development/portal-blue/door-device/node_modules/noble/lib/hci-socket/bindings.js:286:15)
    at emitThree (events.js:136:13)
    at Hci.emit (events.js:217:7)
    at Hci.onSocketData (/home/lastmjs/development/portal-blue/door-device/node_modules/noble/lib/hci-socket/hci.js:497:14)
    at emitOne (events.js:116:13)
```

**Comment by lastmjs** [comment]
I'm doing some debugging, and `uuids` here is not an array like I assume this if statement is expecting it to be, it's a function.

**Comment by lastmjs** [comment]
Foolishness on my part, I wasn't using the `discoverServices` function correctly and was passing in the callback as the first parameter.
