### ISSUE TITLE
cannot find the proximity sensor's UUID on raspberry pi (ReferenceError)

### ISSUE THREAD

**Issue by Pam95** [noble/noble#812]
Hi,
I'm using the estimote proximity beacons for my autonomous vehicle project. The raspberry pi is mounted on the vehicle, so when the vehicle moves the pi detects the proximity sensor ID and the distance between the sensor and the pi. I'm using the noble library on raspbian stretch OS.  The program prints out the macAdress, rssi and distance. 

The issue is that when I tried to print the UUID and txpowerLevel of the each beacon , I got an reference error saying that "advertisment is not defined"
Could someone help me to fix the error. 

Thanks in advance for your help! 

Here is the node.js code that I'm using 
```var noble = require('noble');
const BeaconScanner = require("node-beacon-scanner");
const Noble = require("noble");

noble.on('stateChange', function(state) {
if (state === 'poweredOn')
//noble.startScanning([], true); // any service UUID, allow duplicates
noble.startScanning();
else
noble.stopScanning();
});

noble.on('discover', function(peripheral) {  
var macAddress = peripheral.uuid;
var rss = peripheral.rssi; 
var id = peripheral.id;
var advertisment = peripheral.advertisment; 
var txPowerLevel = advertisement.txPowerLevel;
var serviceUuids = advertisement.serviceUuids;
var txPower = -59 //hard coded power value
  
  if (rss == 0) {
    return -1.0; 
  }
  var ratio = rss*1.0/txPower;
  if (ratio < 1.0) {
    return Math.pow(ratio,10);
  }
  else {
  var distance =  (0.89976)*Math.pow(ratio,7.7095)+ 0.111;   
   console.log('macAddress: ', macAddress, '  rssi', rss, 'distance' ,distance, txPowerLevel, serviceUuids); 
  }
});`

This is the error that I got

`pi@raspberrypi:~/Desktop/ble-project $ sudo node appc.js
/home/pi/ble-project/appc.js:26
var txPowerLevel = advertisement.txPowerLevel;
                   ^

ReferenceError: advertisement is not defined
    at Noble.<anonymous> (/home/pi/ble-project/appc.js:26:20)
    at emitOne (events.js:77:13)
    at Noble.emit (events.js:169:7)
    at Noble.onDiscover (/home/pi/ble-project/node_modules/noble/lib/noble.js:178:10)
    at emitMany (events.js:108:13)
    at emit (events.js:182:7)
    at NobleBindings.onDiscover (/home/pi/ble-project/node_modules/noble/lib/hci-socket/bindings.js:174:10)
    at emitMany (events.js:108:13)
    at emit (events.js:182:7)
    at Gap.onHciLeAdvertisingReport (/home/pi/ble-project/node_modules/noble/lib/hci-socket/gap.js:256:10)`

**Comment by ikivela** [comment]
You don't have variable called **advertisement** (only  advertisment ). So rename your variable.
