### ISSUE TITLE
binding error on osx 10.11.6

### ISSUE THREAD

**Issue by sharkwheels** [noble/noble#814]
Hey-o. So I'm getting the binding error for osx 10.11.6 using Node v8.11.3 and npm 5.6.0. I'm a little unsure how to solve it as I keep seeing this come up in Linux / Ubuntu but not osx. Its been quite a while since I used noble, so just wondering what I'm doing wrong. 

This is what `npm list` gives me after installing noble@1.9.1, and node-gyp@3.7.0:

```
├─┬ noble@1.9.1
│ ├─┬ UNMET OPTIONAL DEPENDENCY bluetooth-hci-socket@0.5.1
│ │ ├── UNMET OPTIONAL DEPENDENCY debug@2.6.9
│ │ ├── nan@2.10.0
│ │ └─┬ UNMET OPTIONAL DEPENDENCY usb@1.3.2
│ │   ├── nan@2.10.0 deduped
│ │   └─┬ UNMET OPTIONAL DEPENDENCY node-pre-gyp@0.10.2
│ │     ├── UNMET OPTIONAL DEPENDENCY detect-libc@1.0.3
│ │     ├── mkdirp@0.5.1 deduped
│ │     ├─┬ UNMET OPTIONAL DEPENDENCY needle@2.2.1
│ │     │ ├── UNMET OPTIONAL DEPENDENCY debug@2.6.9
│ │     │ ├─┬ UNMET OPTIONAL DEPENDENCY iconv-lite@0.4.23
│ │     │ │ └── safer-buffer@2.1.2 deduped
│ │     │ └── UNMET OPTIONAL DEPENDENCY sax@1.2.4
│ │     ├── UNMET OPTIONAL DEPENDENCY nopt@4.0.1
│ │     ├─┬ UNMET OPTIONAL DEPENDENCY npm-packlist@1.1.10
│ │     │ ├─┬ UNMET OPTIONAL DEPENDENCY ignore-walk@3.0.1
│ │     │ │ └── minimatch@3.0.4 deduped
│ │     │ └── UNMET OPTIONAL DEPENDENCY npm-bundled@1.0.3
│ │     ├── npmlog@4.1.2 deduped
│ │     ├─┬ UNMET OPTIONAL DEPENDENCY rc@1.2.8
│ │     │ ├── UNMET OPTIONAL DEPENDENCY deep-extend@0.6.0
│ │     │ ├── UNMET OPTIONAL DEPENDENCY ini@1.3.5
│ │     │ ├── UNMET OPTIONAL DEPENDENCY minimist@1.2.0
│ │     │ └── UNMET OPTIONAL DEPENDENCY strip-json-comments@2.0.1
│ │     ├── rimraf@2.6.2 deduped
│ │     ├── semver@5.3.0 deduped
│ │     └── UNMET OPTIONAL DEPENDENCY tar@4.4.4
│ ├── bplist-parser@0.0.6

```

This is the binding error:

```
module.js:549
    throw err;
    ^

Error: Cannot find module './build/Release/binding.node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nadinelessio/node_modules/xpc-connection/index.js:3:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

Thanks!

**Comment by sharkwheels** [comment]
Well the only thing that solved this for me was nuking node and all my modules off my system totally and then basically re-installing everything. I'll consider this closed.
