### ISSUE TITLE
Index out of range error in processLeAdvertisingReport

### ISSUE THREAD

**Issue by AlCalzone** [noble/noble#831]
```
RangeError: Index out of range
at BluetoothHciSocket.emit (events.js:211:7)
at emitOne (events.js:116:13)
at Hci.onSocketData (/opt/iobroker/node_modules/noble/lib/hci-socket/hci.js:479:12)
at Hci.processLeMetaEvent (/opt/iobroker/node_modules/noble/lib/hci-socket/hci.js:608:10)
at Hci.processLeAdvertisingReport (/opt/iobroker/node_modules/noble/lib/hci-socket/hci.js:643:21)
at Buffer.readInt8 (buffer.js:1103:5)
at checkOffset (buffer.js:977:11)
```
I believe the buffer's length should be checked before reading from it in order to avoid crashing on invalid packets.

**Comment by svogl** [comment]
we hade similar problems and added two try-catch regions around the affected hci and gap code; you might want to give this a try:
https://github.com/voxel-dot-at/noble/commit/75a34d989bd0557bf3239e1cdf2632bf2b4e6d8c

**Comment by johngo7470** [comment]
svogl - Your updates to handle invalid packets, are the cat's meow - thanks!

update: seems I spoke too soon...

```
buffer.js:977
    throw new RangeError('Index out of range');
    ^

RangeError: Index out of range
    at checkOffset (buffer.js:977:11)
    at Uint8Array.Buffer.readUInt8 (buffer.js:1015:5)
    at Hci.onSocketData (/home/pi/node_modules/noble/lib/hci-socket/hci.js:471:34)
    at emitOne (events.js:116:13)
    at BluetoothHciSocket.emit (events.js:211:7)
```
