### ISSUE TITLE
Module version mismatch returns

### ISSUE THREAD

**Issue by ocaduacelab** [noble/noble#844]
Hi. So I'm getting this error on both osx and raspberry pi. I have tried uninstalling and re-installing noble via NPM, I am unsure how to re-build the bluetooth-hci-socket? It was suggested to do that in a different thread, how do you do it?

OSX is using node version 8.13 on High Serria, and on the raspberry pi its also 8.13 on stretch. I'm using NVM to manage node. 

Anyone got a step by step guide for this? 

Because I'm feeling: 

¯\_(ツ)_/¯

Thanks. 

raspberry pi:

```
Error: Module version mismatch. Expected 46, got 57.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/node_modules/bluetooth-hci-socket/lib/native.js:3:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

OSX

```
Error: The module '/Users/ace_lab/node_modules/xpc-connection/build/Release/binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ace_lab/node_modules/xpc-connection/index.js:3:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
```

**Comment by ocaduacelab** [comment]
so as an update, npm rebuild fixes this for OSX. 

On the Rpi so far I've tried:

removing any other nodes via nvm and only having 8.13
npm rebuild
npm rebuild bluetooth-hci-socket
reinstalling the dependencies via apt-get
rm -rf all the node modules, doing npm update, and also re-installing noble
 
I am still getting the module version mismatch error.

**Comment by ocaduacelab** [comment]
Alrighty so apparently you HAVE to do `sudo setcap cap_net_raw+eip $(eval readlink -f 'which node')` for things to work. 

I thought that was optional. I have another pi install where using `sudo node` will run things. 

Guess that's solved.
