### ISSUE TITLE
socket.io-client Issue

### ISSUE THREAD

**Issue by BelkissZroud** [noble/noble#869]
I am trying to send data to server using socket.io-client but it is not working. 

socket code : 

var noble = require('noble');
var beacon_descover = require('./beacon_descover.js');
var io = require('socket.io-client')
var socket = io.connect('http://localhost:8080', {reconnect: true});
var addressToTrack = 'x.x.x.x ';

socket.on('connect', function(){
    console.log('connected to server');
});

noble.on('discover', function(peripheral){
    if(peripheral.uuid == addressToTrack){
        socket.emit('deviceData', {mac: peripheral.uuid, rssi:peripheral.rssi});
    }
});

noble.startScanning([], true)

Eroor : Error: Could not start scanning, state is unknown (not poweredOn)
    at Noble.scan (/home/belkiss/node_modules/noble/lib/noble.js:97:19)
    at Noble.startScanning (/home/belkiss/node_modules/noble/lib/noble.js:126:10)
    at Object.<anonymous> (/home/belkiss/WebstormProjects/Beacon_Project/beacon_streamer.js:24:7)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)

**Comment by EndoMatrix** [comment]
You're most likely receiving this error because `noble.state` is not in the `poweredOn` state. As mentioned in the README:

> **NOTE:** `noble.state` must be `poweredOn` before scanning is started. `noble.on('stateChange', callback(state));` can be used register for state change events.

As suggested, something like the following would avoid this error:

```
noble.on('stateChange', function(state) {
  if (state === 'poweredOn') {
    noble.startScanning([], true);
  }
});
```
