### ISSUE TITLE
Impossible to install noble

### ISSUE THREAD

**Issue by S-Maxime** [noble/noble#901]
Hello everyone, i have a big problem with this package, 

You can see everything here :

```
npm i noble

> usb@1.6.0 install /home/max/Devs/test/node_modules/usb
> prebuild-install --verbose || node-gyp rebuild

prebuild-install info begin Prebuild-install version 5.3.1
prebuild-install info looking for cached prebuild @ /home/max/.npm/_prebuilds/2e98b1-usb-v1.6.0-node-v72-linux-x64.tar.gz
prebuild-install info found cached prebuild 
prebuild-install info unpacking @ /home/max/.npm/_prebuilds/2e98b1-usb-v1.6.0-node-v72-linux-x64.tar.gz
prebuild-install info unpack resolved to /home/max/Devs/test/node_modules/usb/build/Release/usb_bindings.node
prebuild-install info unpack required /home/max/Devs/test/node_modules/usb/build/Release/usb_bindings.node successfully
prebuild-install info install Successfully installed prebuilt binary!

> bluetooth-hci-socket@0.5.1 install /home/max/Devs/test/node_modules/bluetooth-hci-socket
> node-gyp rebuild

make : on entre dans le répertoire « /home/max/Devs/test/node_modules/bluetooth-hci-socket/build »
  CXX(target) Release/obj.target/binding/src/BluetoothHciSocket.o
../src/BluetoothHciSocket.cpp: In static member function ‘static void BluetoothHciSocket::Init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/BluetoothHciSocket.cpp:128:82: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
 get->Set(Nan::New("BluetoothHciSocket").ToLocalChecked(), tmpl->GetFunction());
                                                                             ^
In file included from /home/max/.cache/node-gyp/12.10.0/include/node/node.h:63:0,
                 from /home/max/.cache/node-gyp/12.10.0/include/node/node_buffer.h:25,
                 from ../src/BluetoothHciSocket.cpp:7:
/home/max/.cache/node-gyp/12.10.0/include/node/v8.h:5961:46: note: candidate: v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/max/.cache/node-gyp/12.10.0/include/node/v8.h:5961:46: note:   candidate expects 1 argument, 0 provided
../src/BluetoothHciSocket.cpp: In member function ‘void BluetoothHciSocket::poll()’:
../src/BluetoothHciSocket.cpp:251:95: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
 back(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);
                                                                              ^
In file included from ../src/BluetoothHciSocket.cpp:8:0:
../../nan/nan.h:1045:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../src/BluetoothHciSocket.cpp: In member function ‘void BluetoothHciSocket::emitErrnoError()’:
../src/BluetoothHciSocket.cpp:269:109: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
 or = Local<Function>::Cast(globalObj->Get(Nan::New("Error").ToLocalChecked()));
                                                                             ^
In file included from /home/max/.cache/node-gyp/12.10.0/include/node/v8-internal.h:14:0,
                 from /home/max/.cache/node-gyp/12.10.0/include/node/v8.h:25,
                 from /home/max/.cache/node-gyp/12.10.0/include/node/node.h:63,
                 from /home/max/.cache/node-gyp/12.10.0/include/node/node_buffer.h:25,
                 from ../src/BluetoothHciSocket.cpp:7:
/home/max/.cache/node-gyp/12.10.0/include/node/v8.h:3425:51: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Value> Get(Local<Value> key));
                                                   ^
/home/max/.cache/node-gyp/12.10.0/include/node/v8config.h:311:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/BluetoothHciSocket.cpp:275:72: error: no matching function for call to ‘v8::Function::NewInstance(int, v8::Local<v8::Value> [1])’
   Local<Value> error = errorConstructor->NewInstance(1, constructorArgs);
                                                                        ^
In file included from /home/max/.cache/node-gyp/12.10.0/include/node/node.h:63:0,
                 from /home/max/.cache/node-gyp/12.10.0/include/node/node_buffer.h:25,
                 from ../src/BluetoothHciSocket.cpp:7:
/home/max/.cache/node-gyp/12.10.0/include/node/v8.h:4144:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^~~~~~~~~~~
/home/max/.cache/node-gyp/12.10.0/include/node/v8.h:4144:44: note:   candidate expects 3 arguments, 2 provided
/home/max/.cache/node-gyp/12.10.0/include/node/v8.h:4147:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^~~~~~~~~~~
/home/max/.cache/node-gyp/12.10.0/include/node/v8.h:4147:44: note:   candidate expects 1 argument, 2 provided
../src/BluetoothHciSocket.cpp:282:93: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
 back(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);
                                                                              ^
In file included from ../src/BluetoothHciSocket.cpp:8:0:
../../nan/nan.h:1045:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../src/BluetoothHciSocket.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE BluetoothHciSocket::BindRaw(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/BluetoothHciSocket.cpp:395:34: error: no matching function for call to ‘v8::Value::IntegerValue()’
       devId = arg0->IntegerValue();
                                  ^
In file included from /home/max/.cache/node-gyp/12.10.0/include/node/node.h:63:0,
                 from /home/max/.cache/node-gyp/12.10.0/include/node/node_buffer.h:25,
                 from ../src/BluetoothHciSocket.cpp:7:
/home/max/.cache/node-gyp/12.10.0/include/node/v8.h:2578:40: note: candidate: v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
                                        ^~~~~~~~~~~~
/home/max/.cache/node-gyp/12.10.0/include/node/v8.h:2578:40: note:   candidate expects 1 argument, 0 provided
../src/BluetoothHciSocket.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE BluetoothHciSocket::BindUser(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/BluetoothHciSocket.cpp:417:34: error: no matching function for call to ‘v8::Value::IntegerValue()’
       devId = arg0->IntegerValue();
                                  ^
In file included from /home/max/.cache/node-gyp/12.10.0/include/node/node.h:63:0,
                 from /home/max/.cache/node-gyp/12.10.0/include/node/node_buffer.h:25,
                 from ../src/BluetoothHciSocket.cpp:7:
/home/max/.cache/node-gyp/12.10.0/include/node/v8.h:2578:40: note: candidate: v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
                                        ^~~~~~~~~~~~
/home/max/.cache/node-gyp/12.10.0/include/node/v8.h:2578:40: note:   candidate expects 1 argument, 0 provided
binding.target.mk:109: recipe for target 'Release/obj.target/binding/src/BluetoothHciSocket.o' failed
make: *** [Release/obj.target/binding/src/BluetoothHciSocket.o] Error 1
make : on quitte le répertoire « /home/max/Devs/test/node_modules/bluetooth-hci-socket/build »
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/max/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-60-generic
gyp ERR! command "/home/max/.nvm/versions/node/v12.10.0/bin/node" "/home/max/.nvm/versions/node/v12.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/max/Devs/test/node_modules/bluetooth-hci-socket
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 (node_modules/bluetooth-hci-socket):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ noble@1.9.1
added 4 packages from 4 contributors and audited 107 packages in 4.076s
found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

```

Someone can tell me how to fix this please... ?
I tried to install bluetooth-hci-socket but i get the same error ...
I tried to `node-gyp build`, i get :

```
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
Require stack:
- /usr/share/node-gyp/lib/node-gyp.js
- /usr/share/node-gyp/bin/node-gyp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/usr/share/node-gyp/lib/node-gyp.js:12:10)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/node-gyp/lib/node-gyp.js',
    '/usr/share/node-gyp/bin/node-gyp.js'
  ]
}
```

I tried to remove the `package-lock.json`, `node_modules`, `node_gyp` but same problem...

**Comment by janhaa** [comment]
Duplicate of https://github.com/noble/node-bluetooth-hci-socket/issues/84

Downgrading to node 8.11.1 should work. I don't know why this issue is not fixed in over one year when its a two line fix :/

**Comment by S-Maxime** [comment]
Thanks for your answer, i found @abandonware/noble and bleno, so it's perfect now. ^^

**Comment by Liu-Jinshuai** [comment]
```
npm i bleno2
```
