### ISSUE TITLE
RangeError [ERR_INDEX_OUT_OF_RANGE]: Index out of range

### ISSUE THREAD

**Issue by ns16** [noble/noble#905]
I have the custom device and I want to get its indications. But when I try to subscribe to indications, I get this error:

```
RangeError [ERR_INDEX_OUT_OF_RANGE]: Index out of range
    at checkOffset (buffer.js:1015:11)
    at Buffer.readUInt16LE (buffer.js:1063:5)
    at Gatt.<anonymous> (/home/ns16/projects/my/noble/sample/node_modules/noble/lib/hci-socket/gatt.js:625:24)
    at Gatt.onAclStreamData (/home/ns16/projects/my/noble/sample/node_modules/noble/lib/hci-socket/gatt.js:132:26)
    at AclStream.emit (events.js:185:15)
    at AclStream.push (/home/ns16/projects/my/noble/sample/node_modules/noble/lib/hci-socket/acl-stream.js:35:10)
    at NobleBindings.onAclDataPkt (/home/ns16/projects/my/noble/sample/node_modules/noble/lib/hci-socket/bindings.js:286:15)
    at Hci.emit (events.js:180:13)
    at Hci.onSocketData (/home/ns16/projects/my/noble/sample/node_modules/noble/lib/hci-socket/hci.js:497:14)
    at BluetoothHciSocket.emit (events.js:180:13)
```

This is my code:

```js
const noble = require('noble')

const CUSTOM_SERVICE_UUID = '2a6178017f4211e8b5670800200c9a66'
const ENABLING_MEASUREMENT_MODE_CHARACTERISTIC_UUID = '2a61c62a7f4211e8b5670800200c9a66'
const MEASURED_VALUES_CHARACTERISTIC_UUID = '2a62b0807f4211e8b5670800200c9a66'

noble.on('stateChange', state => {
  console.log(`State changed: ${state}`)
  if (state === 'poweredOn') {
    noble.startScanning()
  }
})

noble.on('discover', peripheral => {
  console.log(`Found device, name: ${peripheral.advertisement.localName}, uuid: ${peripheral.uuid}`)

  if (peripheral.advertisement.localName === 'DEVICE-1') {
    noble.stopScanning()

    peripheral.on('connect', () => console.log('Device connected'))
    peripheral.on('disconnect', () => console.log('Device disconnected'))

    peripheral.connect(error => {
      peripheral.discoverServices([CUSTOM_SERVICE_UUID], (error, services) => {
        console.log(`Found service, name: ${services[0].name}, uuid: ${services[0].uuid}, type: ${services[0].type}`)

        const customService = services[0]

        customService.discoverCharacteristics([ENABLING_MEASUREMENT_MODE_CHARACTERISTIC_UUID, MEASURED_VALUES_CHARACTERISTIC_UUID], (error, characteristics) => {
          console.log(`Found characteristic, name: ${characteristics[0].name}, uuid: ${characteristics[0].uuid}, type: ${characteristics[0].type}`)
          console.log(`Found characteristic, name: ${characteristics[1].name}, uuid: ${characteristics[1].uuid}, type: ${characteristics[1].type}`)

          const enablingMeasurementModeCharacteristic = characteristics[0]
          const measuredValuesCharacteristic = characteristics[1]

          enablingMeasurementModeCharacteristic.write(new Buffer([0x01]), true, error => {
            console.log('Measurement mode is enabled')

            setTimeout(() => {
              measuredValuesCharacteristic.on('data', data => {
                console.log(data)
              })

              measuredValuesCharacteristic.subscribe(error => { //Here is error!
                console.log('Measured values indication enabled')
              })
            }, 1000)
          })
        })
      })
    })
  }
})
```

The error arise in this [line](https://github.com/noble/noble/blob/master/lib/hci-socket/gatt.js#L625). 

I debugged and finded out that the `data` variable each time containes the same buffer <Buffer 09 04 29 00>. The buffer has only four bytes, but above code tries to read fifth and sixth bytes, so the error arise.

I made a fork of this library and want to fix the error in it. How I can change the code correctly?

I fixed as follows:

```js
var value = data.length >= 6 ? data.readUInt16LE(4) : 0x0000;
```

The error doesn't arise, but I don't get the indications. Is this right or wrong?

**Comment by adhavann** [comment]
I am facing the same issue as well! Is there any info related to this !?
