### ISSUE TITLE
UsbDeviceInterface's Device endoints are not always in the default addresses

### ISSUE THREAD

**Issue by khushbooY** [noble/noble#921]
Hi,
    I guess your this line of code contains default endpoint addressess but there are some UsbDeviceInterface's Device endoints that have different address.

  this._usbDevice.open();
  this._usbDeviceInterface = this._usbDevice.interfaces[0];
  this._aclDataOutEndpoint = this._usbDeviceInterface.endpoint(0x02);//like 0x01
  this._hciEventEndpoint = this._usbDeviceInterface.endpoint(0x81);//like 0x83
  this._aclDataInEndpoint = this._usbDeviceInterface.endpoint(0x82);//like 0x81
this._usbDeviceInterface.claim();

Firstly this showed error

Error from process TypeError: Cannot read property 'on' of undefined
    at BluetoothHciSocket.start (D:\exe_Inprocess\bisoft_exe_64\node_modules_x64\node_modules\bluetooth-hci-socket\lib\usb.js:99:29)
    at Hci.init (D:\exe_Inprocess\bisoft_exe_64\node_modules_x64\node_modules\noble\lib\hci-socket\hci.js:102:18)
    at NobleBindings.init (D:\exe_Inprocess\bisoft_exe_64\node_modules_x64\node_modules\noble\lib\hci-socket\bindings.js:82:13)
    at Noble.<anonymous> (D:\exe_Inprocess\bisoft_exe_64\node_modules_x64\node_modules\noble\lib\noble.js:57:24)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 then i changed it to the UsbDeviceInterface's Device endoints then only scanning of devices is not happening?

Could you please help???

**Comment by rzr** [comment]
Try:
https://github.com/abandonware/noble
