### ISSUE TITLE
RangeError: index out of range

### ISSUE THREAD

**Issue by ime011** [noble/noble#927]
I run Noble on the Raspberry Pi 3 (with Bluetooth) and i receive RSSI values from the nearby beacons that i have. However, if noble is ran the whole times i occasionally get the following error. Please help solve this issue. 

/home/pi/node_modules/noble/lib/hci-socket/hci.js:526
    debug('\t\tdata len = ' + len);
    ^
RangeError: index out of range
    at checkOffset (buffer.js:619:11)
    at Buffer.readInt8 (buffer.js:745:5)
    at Hci.processLeAdvertisingReport (/home/pi/node_modules/noble/lib/hci-socket/hci.js:643:21)
    at Hci.processLeMetaEvent (/home/pi/node_modules/noble/lib/hci-socket/hci.js:608:10)
    at Hci.onSocketData (/home/pi/node_modules/noble/lib/hci-socket/hci.js:479:12)
    at emitOne (events.js:77:13)
    at BluetoothHciSocket.emit (events.js:169:7)
pi@raspberrypi:~ $

**Comment by rzr** [comment]
Please try this version:
https://www.npmjs.com/package/@abandonware/noble/v/1.9.2-8

And report issues also to:
https://github.com/abandonware/noble/issues
